import "./globals.css";
import Copy from "@/app/components/copyRight/page";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Copy />
      </body>
    </html>
  );
}
