import "./globals.css";
<<<<<<< HEAD
import Copy from "@/app/components/copyRight/page";

export const metadata = {
  title: "Create Next App",
=======
import Nav from "../components/navBar/page";
import Footer from "../components/footer/page";


export const metadata = {
  title: "Lookupon",
>>>>>>> 16d57ac5f2635857a65eb64e734308d274b53b28
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
<<<<<<< HEAD
        {children}
        <Copy />
      </body>
=======
        <Nav />
        {children}
        <Footer />
        </body>
>>>>>>> 16d57ac5f2635857a65eb64e734308d274b53b28
    </html>
  );
}
