import "./globals.css";
import Nav from "./components/navBar/page";


export const metadata = {
  title: "Lookupon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav />
        {children}
        </body>
    </html>
  );
}
